#include "src/util/algo.h"  // NOLINT(misc-include-cleaner)
#include "src/util/compiler.h"

#include "src/system/br-insn.h"

#include <span>

namespace tlo {
namespace system {
namespace detail {

// Table of all known branch instructions with there assosiated information
// (branch type) + info for decoding them.
// TODO: This should be reworked.

#if TLO_USING_CLANG
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wglobal-constructors"
#endif

// NOLINTBEGIN(hicpp-avoid-c-arrays,modernize-avoid-c-arrays,cppcoreguidelines-avoid-c-arrays)
static constexpr br_insn_desc_t k_br_insn_descs_tbl[] = {
    { "jo_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x70 },
    { "jno_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x71 },
    { "jb_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x72 },
    { "jae_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x73 },
    { "jz_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x74 },
    { "jnz_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x75 },
    { "jbe_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x76 },
    { "ja_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x77 },
    { "js_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x78 },
    { "jns_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x79 },
    { "jp_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7a },
    { "jnp_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7b },
    { "jl_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7c },
    { "jge_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7d },
    { "jle_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7e },
    { "jg_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0x7f },
    { "ret", brtype_t::RET, 0xc2 },
    { "ret", brtype_t::RET, 0xc3 },
    { "int3", brtype_t::INT, 0xcc },
    { "int", brtype_t::INT, 0xcd },
    { "iret", brtype_t::RET, 0xcf },
    { "loop", brtype_t::LOOP, 0xe2 },
    { "jmp_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xe3 },
    { "call_rel32", brtype_t::CALL | brtype_t::REL, 0xe8 },
    { "jmp_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::UNCOND, 0xe9 },
    { "jmp_rel8", brtype_t::JMP | brtype_t::REL | brtype_t::UNCOND, 0xeb },
    { "syscall", brtype_t::INT, 0xf, 0x5 },
    { "sysret", brtype_t::INT | brtype_t::RET, 0xf, 0x7 },
    { "jo_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x80 },
    { "jno_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x81 },
    { "jb_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x82 },
    { "jae_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x83 },
    { "jz_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x84 },
    { "jnz_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x85 },
    { "jbe_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x86 },
    { "ja_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x87 },
    { "js_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x88 },
    { "jns_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x89 },
    { "jp_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8a },
    { "jnp_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8b },
    { "jl_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8c },
    { "jge_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8d },
    { "jle_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8e },
    { "jg_rel32", brtype_t::JMP | brtype_t::REL | brtype_t::COND, 0xf, 0x8f },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x10 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x11 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x12 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x13 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x14 },
    { "call_riprel", brtype_t::CALL | brtype_t::IND | brtype_t::RIPREL, 0xff,
      0x15 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x16 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x17 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x18 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x19 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x1f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x20 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x21 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x22 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x23 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x24 },
    { "jmp_riprel",
      brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND | brtype_t::RIPREL, 0xff,
      0x25 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x26 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x27 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x28 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x29 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2a },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2b },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2c },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2d },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2e },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x2f },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x50 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x51 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x52 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x53 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x54 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x55 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x56 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x57 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x58 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x59 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x5f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x60 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x61 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x62 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x63 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x64 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x65 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x66 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x67 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x68 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x69 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6a },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6b },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6c },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6d },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6e },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0x6f },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x90 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x91 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x92 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x93 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x94 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x95 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x96 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x97 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x98 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x99 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0xff, 0x9f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa0 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa1 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa2 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa3 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa4 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa5 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa6 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa7 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa8 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xa9 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xaa },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xab },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xac },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xad },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xae },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0xff,
      0xaf },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd0 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd1 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd2 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd3 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd4 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd5 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd6 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0xff, 0xd7 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe0 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe1 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe2 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe3 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe4 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe5 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe6 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0xff, 0xe7 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x10 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x11 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x12 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x13 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x14 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x15 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x16 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x17 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x18 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x19 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x1f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x20 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x21 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x22 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x23 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x24 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x25 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x26 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x27 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x28 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x29 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2a },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2b },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2c },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2d },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2e },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x2f },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x50 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x51 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x52 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x53 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x54 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x55 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x56 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x57 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x58 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x59 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x5f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x60 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x61 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x62 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x63 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x64 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x65 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x66 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x67 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x68 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x69 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6a },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6b },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6c },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6d },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6e },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0x6f },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x90 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x91 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x92 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x93 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x94 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x95 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x96 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x97 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x98 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x99 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9a },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9b },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9c },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9d },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9e },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x41, 0xff, 0x9f },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa0 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa1 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa2 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa3 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa4 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa5 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa6 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa7 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa8 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xa9 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xaa },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xab },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xac },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xad },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xae },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x41,
      0xff, 0xaf },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd0 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd1 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd2 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd3 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd4 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd5 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd6 },
    { "call_ind", brtype_t::CALL | brtype_t::IND, 0x41, 0xff, 0xd7 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe0 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe1 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe2 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe3 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe4 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe5 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe6 },
    { "jmp_ind", brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND, 0x41, 0xff,
      0xe7 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x42, 0xff, 0x14 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x42,
      0xff, 0x24 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x42, 0xff, 0x54 },
    { "jmp_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x42, 0xff, 0x64 },
    { "call_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND,
      0x42, 0xff, 0x94 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x42,
      0xff, 0xa4 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x43, 0xff, 0x14 },
    { "jmp_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x43, 0xff, 0x24 },
    { "call_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND,
      0x43, 0xff, 0x54 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x43,
      0xff, 0x64 },
    { "call_dbl_ind", brtype_t::CALL | brtype_t::DBL_IND, 0x43, 0xff, 0x94 },
    { "jmp_dbl_ind", brtype_t::JMP | brtype_t::UNCOND | brtype_t::DBL_IND, 0x43,
      0xff, 0xa4 },
    { "jmp_riprel",
      brtype_t::JMP | brtype_t::IND | brtype_t::UNCOND | brtype_t::RIPREL, 0xf2,
      0xff, 0x25 },
    { "BAD", brtype_t::BAD, 0xff, 0xff, 0xff, 0xff },
};

// NOLINTEND(hicpp-avoid-c-arrays,modernize-avoid-c-arrays,cppcoreguidelines-avoid-c-arrays)


#if TLO_USING_CLANG
# pragma clang diagnostic pop
#endif

// NOLINTNEXTLINE(misc-include-cleaner)
static_assert(std::is_sorted(
    &k_br_insn_descs_tbl[0],
    &k_br_insn_descs_tbl[sizeof(k_br_insn_descs_tbl) /
                         sizeof(k_br_insn_descs_tbl[0])],
    [](br_insn_desc_t const & lhs, br_insn_desc_t const & rhs) -> bool {
        return lhs.lt(rhs);
    }));


const std::span<const br_insn_desc_t> k_br_insn_descs = {
    // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-array-to-pointer-decay,hicpp-no-array-decay,-warnings-as-errors)
    k_br_insn_descs_tbl,
    sizeof(k_br_insn_descs_tbl) / sizeof(k_br_insn_descs_tbl[0]) - 1UL
};


}  // namespace detail
}  // namespace system
}  // namespace tlo
