get_target_property(STATIC_ANALYSIS_TESTS_SOURCES ${STATIC_ANALYSIS_TESTS_SOURCE_LIST} SOURCES)
get_target_property(STATIC_ANALYSIS_IMPLS_SOURCES ${STATIC_ANALYSIS_IMPLS_SOURCE_LIST} SOURCES)

add_custom_target(
  ${STATIC_ANALYSIS_TESTS_TARGET}
  COMMAND ${CLANG_TIDY_EXE}
  ${STATIC_ANALYSIS_TESTS_SOURCES}
  -p=${CMAKE_CURRENT_BINARY_DIR}
)

add_custom_target(
  ${STATIC_ANALYSIS_IMPLS_TARGET}
  COMMAND ${CLANG_TIDY_EXE}
  ${STATIC_ANALYSIS_IMPLS_SOURCES}
  -p=${CMAKE_CURRENT_BINARY_DIR}
)

add_custom_target(${STATIC_ANALYSIS_TARGET}
  DEPENDS ${STATIC_ANALYSIS_IMPLS_TARGET} ${STATIC_ANALYSIS_TESTS_TARGET}
)

add_custom_target(${STATIC_ANALYSIS_PARALLEL_TARGET}
  DEPENDS ${STATIC_ANALYSIS_IMPLS_PARALLEL_TARGET} ${STATIC_ANALYSIS_TESTS_PARALLEL_TARGET}
)
